// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Automatically generated by addcopyright.py at 01/29/2013
// Apache License, Version 2.0 (the "License"); you may not use this
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// Automatically generated by addcopyright.py at 04/03/2012
package com.cloud.wds.api;

import com.cloud.agent.api.Command;

/**
 * Created by Raghav on 8/13/2015.
 */
public class ImportImageCommand extends Command {

    private static final int timeout = 10000;

    private String installImageFile;
    private String bootImageFile;
    private String bootImageName;
    private String installImageName;
    private String clientUnattendFile;
    private String imageUnattendFile;
    private String imageGroupName;
    private String architecture;
    private String singleImageName;

    private Long templateId;
    private Long hostId;

    public String getInstallImageFile() {
        return installImageFile;
    }

    public void setInstallImageFile(String installImageFile) {
        this.installImageFile = installImageFile;
    }

    public String getBootImageFile() {
        return bootImageFile;
    }

    public void setBootImageFile(String bootImageFile) {
        this.bootImageFile = bootImageFile;
    }

    public String getBootImageName() {
        return bootImageName;
    }

    public void setBootImageName(String bootImageName) {
        this.bootImageName = bootImageName;
    }

    public String getInstallImageName() {
        return installImageName;
    }

    public void setInstallImageName(String installImageName) {
        this.installImageName = installImageName;
    }

    public String getClientUnattendFile() {
        return clientUnattendFile;
    }

    public void setClientUnattendFile(String clientUnattendFile) {
        this.clientUnattendFile = clientUnattendFile;
    }

    public String getImageUnattendFile() {
        return imageUnattendFile;
    }

    public void setImageUnattendFile(String imageUnattendFile) {
        this.imageUnattendFile = imageUnattendFile;
    }

    public String getImageGroupName() {
        return imageGroupName;
    }

    public void setImageGroupName(String imageGroupName) {
        this.imageGroupName = imageGroupName;
    }

    public String getArchitecture() {
        return architecture;
    }

    public void setArchitecture(String architecture) {
        this.architecture = architecture;
    }

    public String getSingleImageName() {
        return singleImageName;
    }

    public void setSingleImageName(String singleImageName) {
        this.singleImageName = singleImageName;
    }

    public Long getTemplateId() {
        return templateId;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public Long getHostId() {
        return hostId;
    }

    public void setHostId(Long hostId) {
        this.hostId = hostId;
    }

    public ImportImageCommand(String installImageFile, String bootImageFile, String bootImageName, String installImageName, String clientUnattendFile, String imageUnattendFile, String imageGroupName, String architecture, String singleImageName, Long templateId, Long hostId) {
        this.setWait(timeout);
        this.installImageFile = installImageFile;
        this.bootImageFile = bootImageFile;
        this.bootImageName = bootImageName;
        this.installImageName = installImageName;
        this.clientUnattendFile = clientUnattendFile;
        this.imageUnattendFile = imageUnattendFile;
        this.imageGroupName = imageGroupName;
        this.architecture = architecture;
        this.singleImageName = singleImageName;

        this.templateId = templateId;
        this.hostId = hostId;
    }

    @Override
    public boolean executeInSequence() {
        return true;
    }
}