// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Automatically generated by addcopyright.py at 01/29/2013
package com.cloud.moonshot.manager;

import com.cloud.moonshot.api.DeleteMoonShotChassisCmd;
import com.cloud.moonshot.api.ImportMoonShotChassisCmd;
import com.cloud.moonshot.api.ListMoonShotChassisCmd;
import com.cloud.moonshot.api.ListMoonShotChassisResponse;
import com.cloud.moonshot.api.ListMoonShotNodeResponse;
import com.cloud.moonshot.api.ListMoonShotNodesCmd;
import com.cloud.moonshot.api.MoonShotChassisResponse;
import com.cloud.moonshot.api.SyncMoonShotChassisCmd;
import com.cloud.moonshot.api.SyncMoonShotChassisResponse;
import com.cloud.moonshot.api.UpdateMoonShotChassisCmd;
import com.cloud.utils.Pair;
import com.cloud.utils.component.Manager;
import com.cloud.utils.component.PluggableService;

import java.util.List;

public interface MoonShotBareMetalManager extends Manager, PluggableService {

    String CARTRIDGE_NUMBER = "cartridgeNumber";
    String NODE_NUMBER = "nodeNumber";
    String CARTRIDGE_NODE_LOCATION = "CartridgeNodeLocation";

    MoonShotChassisResponse addMoonShotChassis(ImportMoonShotChassisCmd cmd);

    Pair<? extends List<ListMoonShotChassisResponse>, Integer> listMoonShotChassis(ListMoonShotChassisCmd cmd);

    Pair<? extends List<ListMoonShotNodeResponse>, Integer> listMoonShotNode(ListMoonShotNodesCmd cmd);

    List<SyncMoonShotChassisResponse> syncMoonShotChassis(SyncMoonShotChassisCmd cmd);

    boolean deleteMoonshotNode(String uuid);

    boolean deleteMoonshotChassis(DeleteMoonShotChassisCmd cmd);

    boolean updateMoonshotChassis(UpdateMoonShotChassisCmd cmd);
}
