// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Automatically generated by addcopyright.py at 01/29/2013
// Apache License, Version 2.0 (the "License"); you may not use this
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// Automatically generated by addcopyright.py at 04/03/2012
package com.cloud.moonshot.api;

import com.cloud.moonshot.manager.MoonShotBareMetalManager;
import org.apache.cloudstack.acl.RoleType;
import org.apache.cloudstack.api.APICommand;
import org.apache.cloudstack.api.ApiErrorCode;
import org.apache.cloudstack.api.BaseAsyncCmd;
import org.apache.cloudstack.api.Parameter;
import org.apache.cloudstack.api.ServerApiException;
import org.apache.cloudstack.context.CallContext;
import org.apache.log4j.Logger;

import javax.inject.Inject;

/**
 * Created by Raghav on 8/13/2015.
 */
@APICommand(name = "importMoonShotChassis", description = "Imports Moonshot Chassis", responseObject = MoonShotChassisResponse.class,
        requestHasSensitiveInfo = false, responseHasSensitiveInfo = false, authorized = {RoleType.Admin})
public class ImportMoonShotChassisCmd extends BaseAsyncCmd {

    private static final String s_name = "importmoonshotchassisresponse";

    public static final Logger s_logger = Logger.getLogger(ImportMoonShotChassisCmd.class);

    @Inject
    MoonShotBareMetalManager _moonShotBareMetalMgr;

    @Parameter(name = "name", required = true, description = "Name of Moonshot Chassis")
    private String name;

    @Parameter(name = "url", required = false, description = "URL of Moonshot Chassis, should not be passed when passing id")
    private String url;

    @Parameter(name = "username", required = false, description = "Username of Moonshot Chassis, should not be passed when passing id")
    private String username;

    @Parameter(name = "password", required = false, description = "Password of Moonshot Chassis, should not be passed when passing id")
    private String password;

    @Parameter(name = "addhosts", required = false, description = "Whether to create hosts of Moonshot nodes")
    private String addHosts = "true";

    @Parameter(name = "importnodes", required = false, description = "Whether to import Moonshot nodes")
    private String importNodes = "true";

    @Parameter(name = "clusterid", required = true, description = "Id of cluster")
    private String clusterId;

    @Parameter(name = "hosttag", required = true, description = "Host tag to be given to the hosts created for Moonshot nodes")
    private String hostTag;

    @Parameter(name = "id", required = false, description = "Id of the moonshot chassis, this should only be passed along with cartridges parameter")
    private String id;

    @Parameter(name = "cartridges", required = false, description = "Comma separated short names of cartridges to be imported, ex. C1,C2,C6")
    private String cartridges;

    public ImportMoonShotChassisCmd() {
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClusterId() {
        return clusterId;
    }

    public void setClusterId(String clusterId) {
        this.clusterId = clusterId;
    }

    public String getHostTag() {
        return hostTag;
    }

    public void setHostTag(String hostTag) {
        this.hostTag = hostTag;
    }

    public String getAddHosts() {
        return addHosts;
    }

    public void setAddHosts(String addHosts) {
        this.addHosts = addHosts;
    }

    public String getImportNodes() {
        return importNodes;
    }

    public void setImportNodes(String importNodes) {
        this.importNodes = importNodes;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCartridges() {
        return cartridges;
    }

    public void setCartridges(String cartridges) {
        this.cartridges = cartridges;
    }

    @Override
    public String getCommandName() {
        return s_name;
    }

    @Override
    public long getEntityOwnerId() {
        return CallContext.current().getCallingAccount().getId();
    }

    @Override
    public String getEventType() {
        return "BAREMETAL.CHASSIS.IMPORT";
    }

    @Override
    public String getEventDescription() {
        return "Importing Moonshot Chassis";
    }

    @Override
    public void execute() {
        try {
            MoonShotChassisResponse rsp = _moonShotBareMetalMgr.addMoonShotChassis(this);
            this.setResponseObject(rsp);
        } catch (Exception e) {
            s_logger.warn(String.format("unable to import Moonshot Chassis [%s]", getUrl()), e);
            throw new ServerApiException(ApiErrorCode.INTERNAL_ERROR, e.getMessage());
        }
    }
}
